name: flutter_project_calendar
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  # Core packages
  provider: ^6.0.5
  cupertino_icons: ^1.0.8

  # Calendar functionality
  table_calendar: ^3.0.9
  
  # Google APIs
  google_sign_in: ^6.1.5
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.0
  http: ^0.13.0

  # Firebase
  firebase_core: ^2.18.0
  cloud_firestore: ^4.9.0
  cloud_firestore_web: ^3.7.0
  firebase_auth: ^4.11.0
  firebase_auth_web: ^5.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true